kind: pipeline
name: default
workspace:
    base: /go
    path: src/github.com/fanux/sealbuild

steps:
- name: build
  image: golang:1.13
  commands:
      - go get && go build -o sealbuild

- name: publish
  image: plugins/github-release
  settings:
    api_key:
        from_secret: git-release-token
    files: sealbuild
    title: ${DRONE_TAG}
    note: README.md
  when:
     event:
     - tag
